### ISSUE TITLE
About dataset 

### ISSUE THREAD

**Issue by szh404** [MarsZhaoYT/Sar2Opt-Heterogeneous-Dataset#5]
I would like to know if any denoising processing has been applied to the SAR images in your dataset?

If so, could you provide details about the specific denoising techniques used? In my current experiments, I am achieving good results only when using your dataset, while the performance on other datasets is quite poor. 

I would like to make the other datasets as similar to yours as possible. 

Thank you.

Best wishes!

**Comment by MarsZhaoYT** [comment]
Hi, glad to hear that our dataset is useful for your research. 

During the preprocessing, the mean filtering is applied to suppress the speckle noise of SAR images. Maybe you can try it on the other datasets, as well as some other simple denoising algorithms. 

Best wishes : )

**Comment by szh404** [comment]
> Hi, glad to hear that our dataset is useful for your research.
> 
> During the preprocessing, the mean filtering is applied to suppress the speckle noise of SAR images. Maybe you can try it on the other datasets, as well as some other simple denoising algorithms.
> 
> Best wishes : )
